# Generated by Django 3.1.6 on 2021-03-05 09:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=app.models.recipe_image_file_path),
        ),
    ]
